const RENDERERS_VIEW_WIDTH = 1100;
const RENDERERS_VIEW_HEIGHT = 700;
const MOCKUP_BACKGROUND_SCALE = 0.32;
const MOCKUP_BACKGROUND_VARIANT = 2;

export {
  RENDERERS_VIEW_WIDTH,
  RENDERERS_VIEW_HEIGHT,
  MOCKUP_BACKGROUND_SCALE,
  MOCKUP_BACKGROUND_VARIANT,
};
