const SCREEN_WIDTH = 1100;
const SCREEN_HEIGHT = 700;
const MOCKUP_BACKGROUND_SCALE = 0.32;
const MOCKUP_BACKGROUND_VARIANT = 2;

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  MOCKUP_BACKGROUND_SCALE,
  MOCKUP_BACKGROUND_VARIANT,
};
